const orderContent = {
    translations: {
        ua: {
            infoAbout: 'Інформація про замовлення',
            items: 'Товари',
            payment: 'Оплата',
            status: 'Статус',
            method: 'Метод',
            amount: 'Сума',
            approved: 'Підтверждено',
            pending: 'Обробляється',
            refunded: 'Скасовано',
            payByCard : 'Оплата картою',
            payOnDelivery: 'Оплата при отриманні',
            delivery: 'Доставка',
            deliveryService: 'Сервіс доставки',
            novaPoshta: 'Нова Пошта',
            deliveryDate: 'Орієнтовна дата отримання',
            receiptPlace: 'Місце отримання',
            city: 'Місто',
            region: 'Область',
            office: 'Номер відділення',
            toWareHouse: 'На відділення',
            toAddress: 'На адресу',
            serviceType: 'Тип доставки',
            street: 'Вулиця',
            house: 'Дім',
            apartment: 'Вулиця',
            clientInfo: 'Інформація про клієнта',
            name: 'Ім\'я',
            email: 'Email',
            phone: 'Номер',
        },
        eng: {
            infoAbout: 'Order Information',
            items: 'Goods',
            payment: 'Payment',
            status: 'Status',
            method: 'Method',
            amount: 'Amount',
            approved: 'Approved',
            pending: 'Processing',
            refunded: 'Cancelled',
            payByCard : 'Pay by card',
            payOnDelivery: 'Pay on delivery',
            delivery: 'Delivery',
            deliveryService: 'Delivery Service',
            novaPoshta: 'New Post',
            deliveryDate: 'Estimated delivery date',
            receiptPlace: 'Receipt Place',
            city: 'City',
            region: 'Region',
            office: 'Department number',
            toWareHouse: 'To Branch',
            toAddress: 'To address',
            serviceType: 'Delivery Type',
            street: 'Street',
            house: 'House',
            apartment: 'Street',
            clientInfo: 'Client Info',
            name: 'My name',
            email: 'Email',
            phone: 'Number',
        },
        ru: {
            infoAbout: 'Информация о заказах',
            items: 'Товары',
            payment: 'Оплата',
            status: 'Статус',
            method: 'Метод',
            amount: 'Сумма',
            approved: 'Подтверждено',
            pending: 'Обрабатывается',
            refunded: 'Отменено',
            payByCard : 'Оплата картой',
            payOnDelivery: 'Оплата при получении',
            delivery: 'Доставка',
            deliveryService: 'Сервис доставки',
            novaPoshta: 'Новая Почта',
            deliveryDate: 'Ориентировочная дата получения',
            receiptPlace: 'Место получения',
            city: 'Город',
            region: 'Область',
            office: 'Номер отделения',
            toWareHouse: 'На отделение',
            toAddress: 'На адрес',
            serviceType: 'Тип доставки',
            street: 'Улица',
            house: 'Дом',
            apartment: 'Улица',
            clientInfo: 'Информация о клиенте',
            name: 'Имя',
            email: 'Email',
            phone: 'Номер',
        }
    }
}

export default orderContent

// const _orderContent = {
//     translations: {
//         ua: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         },
//         eng: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         },
//         ru: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         }
//     }
// }