import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.sass'
import Nav from "../components/nav/nav.component";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Unamour</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Nav/>
        </div>
    )
}

export default Home
