import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Nav from "../components/nav/nav.component";
import Footer from "../components/footer/footer.component";
import CookieComponent from "../components/cookie/cookie.component";

const Home: NextPage = () => {
    return (
        <div className={'container'}>
            <Head>
                <title>Unamour</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        </div>
    )
}

export default Home
