const orderContent = {
    translations: {
        ua: {
            infoAbout: 'Інформація про замовлення',
            items: 'Товари',
            payment: 'Оплата',
            status: 'Статус',
            method: 'Метод',
            amount: 'Сума',
            approved: 'Підтверждено',
            pending: 'Обробляється',
            payByCard : 'Оплата картою',
            payOnDelivery: 'Оплата при отриманні',
            delivery: 'Доставка',
            deliveryService: 'Сервіс доставки',
            novaPoshta: 'Нова Пошта',
            deliveryDate: 'Орієнтовна дата отримання',
            receiptPlace: 'Місце отримання',
            city: 'Місто',
            region: 'Область',
            office: 'Номер відділення',
            toWareHouse: 'На відділення',
            toAddress: 'На адресу',
            serviceType: 'Тип доставки',
            street: 'Вулиця',
            house: 'Дім',
            apartment: 'Вулиця',
            clientInfo: 'Інформація про клієнта',
            name: 'Ім\'я',
            email: 'Email',
            phone: 'Номер',
        },
        eng: {
            infoAbout: 'Інформація про замовлення',
            items: 'Товари',
            payment: 'Оплата',
            status: 'Статус',
            method: 'Метод',
            amount: 'Сума',
            approved: 'Підтверждено',
            pending: 'Обробляється',
            payByCard : 'Оплата картою',
            payOnDelivery: 'Оплата при отриманні',
            delivery: 'Доставка',
            deliveryService: 'Сервіс доставки',
            novaPoshta: 'Нова Пошта',
            deliveryDate: 'Орієнтовна дата отримання',
            receiptPlace: 'Місце отримання',
            city: 'Місто',
            region: 'Область',
            office: 'Номер відділення',
            toWareHouse: 'На відділення',
            toAddress: 'На адресу',
            serviceType: 'Тип доставки',
            street: 'Вулиця',
            house: 'Дім',
            apartment: 'Вулиця',
            clientInfo: 'Інформація про клієнта',
            name: 'Ім\'я',
            email: 'Email',
            phone: 'Номер',
        },
        ru: {
            infoAbout: 'Інформація про замовлення',
            items: 'Товари',
            payment: 'Оплата',
            status: 'Статус',
            method: 'Метод',
            amount: 'Сума',
            approved: 'Підтверждено',
            pending: 'Обробляється',
            payByCard : 'Оплата картою',
            payOnDelivery: 'Оплата при отриманні',
            delivery: 'Доставка',
            deliveryService: 'Сервіс доставки',
            novaPoshta: 'Нова Пошта',
            deliveryDate: 'Орієнтовна дата отримання',
            receiptPlace: 'Місце отримання',
            city: 'Місто',
            region: 'Область',
            office: 'Номер відділення',
            toWareHouse: 'На відділення',
            toAddress: 'На адресу',
            serviceType: 'Тип доставки',
            street: 'Вулиця',
            house: 'Дім',
            apartment: 'Вулиця',
            clientInfo: 'Інформація про клієнта',
            name: 'Ім\'я',
            email: 'Email',
            phone: 'Номер',
        }
    }
}

export default orderContent

// const _orderContent = {
//     translations: {
//         ua: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         },
//         eng: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         },
//         ru: {
//             infoAbout: 'Інформація про замовлення',
//             items: 'Товари',
//             payment: 'Оплата',
//             status: 'Статус',
//             method: 'Метод',
//             amount: 'Сума',
//             approved: 'Підтверждено',
//             pending: 'Обробляється',
//             payByCard : 'Оплата картою',
//             payOnDelivery: 'Оплата при отриманні',
//             delivery: 'Доставка',
//             deliveryService: 'Сервіс доставки',
//             novaPoshta: 'Нова Пошта',
//             deliveryDate: 'Орієнтовна дата отримання',
//             receiptPlace: 'Місце отримання',
//             city: 'Місто',
//             region: 'Область',
//             office: 'Номер відділення',
//             toWareHouse: 'На відділення',
//             toAddress: 'На адресу',
//             serviceType: 'Тип доставки',
//             street: 'Вулиця',
//             house: 'Дім',
//             apartment: 'Вулиця',
//             clientInfo: 'Інформація про клієнта',
//             name: 'Ім\'я',
//             email: 'Email',
//             phone: 'Номер',
//         }
//     }
// }